### ISSUE TITLE
About ntb_transport issue

### ISSUE THREAD

**Issue by g1218244** [davejiang/linux#1]
Hi davejiang,
I try to test the virtual Ethernet over NTB function in our system by iPerf.
But when I run "modporbe ntb_transport dyndbg=+p" command, dmesg will shows "Unable to set mw1 translation" error.
This error will cause ntb link disable, so I can't ping to each other node in our system.
I trace your code and found the mw->dma_addr will get 0x176700000 after running dma_alloc_coherent() at line 686 of ntb_transport.c.
But the input parameter “addr” of intel_ntb_mw_set_trans() is 0x176700000, so it will return –EINVAL error when runs to line 904 of ntb_hw_intel.c.
Do you know how to solve this issue to let me use iPerf to check the function?
Thank you.

**Comment by davejiang** [comment]
Something doesn't seem right. What is your BAR configuration for the BARs in BIOS? And you are using the branch off of the github?

Also, can you please go through the startup guide and make sure everything looks ok? Thanks.
https://github.com/davejiang/linux/wiki/Intel-NTB-Startup-Guide

**Comment by g1218244** [comment]
Hi,
I use Broadwell CPU and my BIOS setting as below:
Non-Transparent Bridg : NTB to NTB
Enable NTB BARs : Enabled
Enable SPLIT BARs : Enabled
Primary BAR2/3 Size : 22
Primary BAR4 Size : 20
Primary BAR5 Size : 20
Secondary BAR2/3 Size : 22
Secondary BAR4 Size : 20
Secondary BAR5 Size : 20
Crosslink control Ove : one node for DSD/USP, another for USD/DSP
IOATDMA : enabled
VT-d : enabled

I used the NTB driver which is build in kernel 4.6.3 and I follow your startup guide step by step to check the NTB link status is up before loading ntb_transport.

But after loading ntb_transport, dmesg still shows Unable to set mw1 translation.

Do I need to set CMA setting as below?
CONFIG_CMA_AREAS=2
CONFIG_CMA_SIZE_MBYTES=4
CONFIG_CMA_SIZE_SEL_MBYTES=y
CONFIG_CMA_ALIGNMENT=10

My config setting about CMA just as below:
CONFIG_CMA=y
CONFIG_CMA_AREAS=7

Is any effect about CMA setting?

By the way, the following is my NTB info.
NTB Device Information:
Connection Topology -   NTB_TOPO_B2B_USD
B2B MW Idx -        2
B2B Offset -        0x0
BAR4 Split -        yes
NTB CTL -       0x0000
LNK STA -       0xb883
Link Status -       Up
Link Speed -        PCI-E Gen 3
Link Width -        x8
Memory Window Count -   2
Scratchpad Count -  16
Doorbell Count -    15
Doorbell Vector Count - 4
Doorbell Vector Shift - 5
Doorbell Valid Mask -   0x7fff
Doorbell Link Mask -    0x8000
Doorbell Mask Cached -  0x7fff
Doorbell Mask -     0x7fff
Doorbell Bell -     0x0

NTB Incoming XLAT:
XLAT23 -        0x00000007fc000000
XLAT4 -         0x32e00000
XLAT5 -         0x0000
LMT23 -         0x0000000000000000
LMT4 -          0x0000
LMT5 -          0x40000000

NTB Outgoing B2B XLAT:
B2B XLAT23 -        0x2000000000000000
B2B XLAT4 -     0x20000000
B2B XLAT5 -     0x40000000
B2B LMT23 -     0x0000000000000000
B2B LMT4 -      0x0000
B2B LMT5 -      0x0000

NTB Secondary BAR:
SBAR01 -        0x000000004000000c
SBAR23 -        0x200000000000000c
SBAR4 -         0x20000000
SBAR5 -         0x40000000

XEON NTB Statistics:
Upstream Memory Miss -  6

XEON NTB Hardware Errors:
DEVSTS -        0x0000
LNKSTS -        0xb083
UNCERRSTS -     0x100000
CORERRSTS -     0x10c0

Thank you.

**Comment by davejiang** [comment]
Ok you need to use the branch in my github. Upstream does not have the workaround patch and does not understand split BAR. That could explain why your MW1 isn't setting up correctly. It's a 32bit BAR and you are trying to write a 64bit addr to the XLAT register. You shouldn't run into CMA issues at this point. I also would suggest you turn off VTd for now. There are BIOS issues with VTd. We have root caused it and have a fix but I am uncertain if your BIOS vendor has picked up the fix yet or not.

**Comment by g1218244** [comment]
After I replace the ntb folder in kernel 4.6.3 with your github brach, the ntb_transport does not shows the MW1 error message and I can use iPerf to test virtual Ethernet over NTB.
But after system reboot , I want to check if ntb_perf work.
After loading ntb_perf and enter "echo 1 > /sys/kernel/debug/ntb_perf/XXXX:XX:XX.X/run" command to run ntb_perf, the terminal does not respond and dmesg does not shows any error message.
But I remember ntb_perf can work successful in kernel 4.6.3.
Is ntb_perf work in this branch?

Thank you!

**Comment by davejiang** [comment]
That's odd. I just tested and have no issues. Can you please run the kernel instead of replacing the folder. Either that or cherry pick the workaround patch to your 4.6.3 kernel. Thanks.

**Comment by g1218244** [comment]
Hi, 
I used your kernel 4.6.0+ to check ntb_transport and ntb_perf.
But I make olddefconfig with my old 4.2 kernel .config before to do make menuconfig with your kernel. 
There have some strange things about NTB device info before check NTB functions.
The following is my NTB device info:
NTB Device Information:
Connection Topology -   NTB_TOPO_B2B_DSD
BAR4 Split -        yes
NTB CTL -       0x0000
LNK STA -       0xb883
Link Status -       Down
Memory Window Count -   1
Scratchpad Count -  16
Doorbell Count -    14
Doorbell Vector Count - 4
Doorbell Vector Shift - 5
Doorbell Valid Mask -   0x3fff
Doorbell Link Mask -    0x8000
Doorbell Mask Cached -  0x3fff
Doorbell Mask -     0x3fff
Doorbell Bell -     0x0

NTB Incoming XLAT:
XLAT23 -        0x0000000000000000
XLAT4 -         0xfee00000
XLAT5 -         0x0000
LMT23 -         0x2000000000000000
LMT4 -          0x20100000
LMT5 -          0x40000000

NTB Outgoing B2B XLAT:
B2B XLAT23 -        0x2000000000000000
B2B XLAT4 -     0x20000000
B2B XLAT5 -     0x40000000
B2B LMT23 -     0x0000000000000000
B2B LMT4 -      0x0000
B2B LMT5 -      0x0000

NTB Secondary BAR:
SBAR01 -        0x000000000000000c
SBAR23 -        0x200000000000000c
SBAR4 -         0x20000000
SBAR5 -         0x40000000

XEON NTB Statistics:
Upstream Memory Miss -  0

XEON NTB Hardware Errors:
DEVSTS -        0x0000
LNKSTS -        0xb083
UNCERRSTS -     0x0000
CORERRSTS -     0x00c1

My LNK STA is 0xb883 and LNKSTS is 0xb083, but why Link Status is Down?
In addition, Ntb_transport and ntb_perf can't work too.

**Comment by davejiang** [comment]
I'm not sure what's going on with you but I tested everything yesterday and have no issue. Please email me at dave.jiang@intel.com. Can you turn dynamic debug on for the hardware driver?
modprobe ntb_hw_intel dyndbg=+p and provide the dmesg after you have the transport loaded on both sides? Thanks! It is possible that the MSIX data for the workaround are not being exchanged for whatever reason. You said things worked with your "hybrid" kernel correct?

**Comment by hospitality680816** [comment]
I have one question about the sentence of "
That could explain why your MW1 isn't setting up correctly. It's a 32bit BAR and you are trying to write a 64bit addr to the XLAT register. "

The only solution is to use the branch in your github ?
Is it possible to tell the BIOS engineer to do modification for BAR setting ?

**Comment by hospitality680816** [comment]
Actually I create an Intel IPS ticket (number: 00167780) to track ntb problem recently, which is similar to this one discussed by g1218244

**Comment by hospitality680816** [comment]
When loading ntb_transport.ko dyndbg=+p, it shows:

[ 1403.834290] ntb_hw_intel 0000:00:03.0: Remote max number of qps = 2
[ 1403.834293] ntb_hw_intel 0000:00:03.0: Remote number of mws = 2
[ 1403.834297] ntb_hw_intel 0000:00:03.0: Remote MW0 size = 0x400000
[ 1403.835003] ntb_hw_intel 0000:00:03.0: Remote MW1 size = 0x100000
[ 1403.835176] ntb_hw_intel 0000:00:03.0: **Unable to set mw1 translation**

Test environment:
1).
Grangeville with ntb at side A  <-----Gen1x8----------> Grangeville with ntb at side B
                                                         
2) CPU: Grangeville, 24 cpu cores with 1500 Mhz
3) OS: Ubuntu 16.04 , 4.8.0-41-generic
4) ntb driver: Linux built-in ntb driver

5).
At side A (downstream)
Connection Topology -   NTB_TOPO_B2B_DSD
B2B MW Idx -            2
B2B Offset -            0x0
BAR4 Split -            yes
NTB CTL -               0x0000
LNK STA -               0x3081
Link Status -           Up
Link Speed -            PCI-E Gen 1
Link Width -            x8

At side B (upstream)
Connection Topology -   NTB_TOPO_B2B_DSD
B2B MW Idx -            2
B2B Offset -            0x0
BAR4 Split -            yes
NTB CTL -               0x0000
LNK STA -               0x3081
Link Status -           Up
Link Speed -            PCI-E Gen 1
Link Width -            x8

6).
Here are the current BAR address assignment in PCIe configuration header at both side A and B of tested targets.

00:03.0 Bridge: Intel Corporation Device 6f0d (rev 04)
        Subsystem: Intel Corporation Device 0000
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Interrupt: pin A routed to IRQ 29
        Region 0: Memory at f0600000 (64-bit, prefetchable) [size=64K]  <== BAR0/1 , offset 0x10
        Region 2: Memory at f0500000 (64-bit, prefetchable) [size=4M]   <== BAR2/3 , offset 0x18
        Region 4: Memory at fb600000 (32-bit, non-prefetchable) [size=1M] <==BAR4 , offset 0x20
        Region 5: Memory at fb500000 (32-bit, non-prefetchable) [size=1M] <==BAR5 , offset 0x24
        Capabilities: <access denied>
        Kernel driver in use: ntb_hw_intel
        Kernel modules: ntb_hw_intel

**Comment by davejiang** [comment]
If you are getting MW1 config error, that means you are not using my NTB
branch and is using upstream kernel. MW1 is not meant to be used as another
BAR. It's used to configure a workaround for the hardware errata. So
there's no proper split BAR support upstream. Also, the latest is a 4.10
kernel, not 4.6. Please test on that. Thanks!

On Thu, Mar 16, 2017 at 7:41 AM, hospitality680816 <notifications@github.com

**Comment by hospitality680816** [comment]
Please allow me to send you another info from Intel PAE by mail about NTB brings up because the content is private.

**Comment by davejiang** [comment]
Please email me at dave.jiang@intel.com.

On Thu, Mar 16, 2017 at 9:12 AM, hospitality680816 <notifications@github.com
