### ISSUE TITLE
ntb_netdev TCP problem

### ISSUE THREAD

**Issue by ComiXZonE** [davejiang/linux#2]
Hello, I'm using ntb_transport and ntb_netdev drivers to enable communication between two hosts using Switchtec PFX PCIe Switch.

After assigning IP addresses to the virtual eth interfaces of both hosts and successfully pinging each other I tried testing the connection using iperf3.  However, when using TCP as a transport protocol, only certain random number of packets gets sent after which the connection breaks. Wireshark states that a few spurious retransmission happens in those moments followed by Dup ACKs from the destination. After that ARP from the destination keeps asking where the source is and there are some keep-alive messages sent from the source address to destination address, it is a mess really. I am attaching a screenshot of the Wireshark log.

![Wireshark_log](https://user-images.githubusercontent.com/15148215/54698565-ce685180-4b2f-11e9-8a0d-81123153e9cc.png)

Has this kind of behavior been observed before? Note that this does not happen with UDP as a transport protocol. Yes, there are some packet drops here and there but the connection is pretty much stable in that case.

Thank you in advance.

**Comment by davejiang** [comment]
Hi, I know nothing about the switchtec hardware. I suggest you email the
ntb mailing list and hopefully Logan Gunthorpe who maintains the switchtec
driver can answer you.

**Comment by ComiXZonE** [comment]
Hi, sorry for bothering you, I will ask there.

Thank you.
